### ISSUE TITLE
React Workshop HW#1

### ISSUE THREAD

**Issue by leobyeon** [p0x6/holberton-react-workshop-homework#1]
1) https://imgur.com/RAIVaqO
2a) "Closure is the combination of a function and the lexical environment within which that function was declared" - MDN
2b) Closure is the space/designation the lexical environment created within a function occupies. For a language like Javascript where there are no private variables, this becomes a way to create "private" variables that are inaccessible to contexts (scopes) that are outside the scope in which they were declared. For example, if I declare the variable "a" within a function called "foo," it is not possible to access that variable from outside the "foo" function. This can protect variables from being accessed directly or being overwritten.
3c) https://jsfiddle.net/8gx1Lnhj/

Typescript
1) https://jsfiddle.net/1gredxt2/
2) https://jsfiddle.net/bw7zu4qh/1/
3) https://jsfiddle.net/ye7rgx0q/
4) https://jsfiddle.net/2ecrpjdv/1/
5) https://jsfiddle.net/zxr2ajcf/
6) https://jsfiddle.net/x42tugho/
7) https://jsfiddle.net/za73yL06/
8) https://jsfiddle.net/92Lhsaoq/

@p0x6

**Comment by p0x6** [comment]
LGTM!
