### ISSUE TITLE
HW1

### ISSUE THREAD

**Issue by Rd-Feng** [p0x6/holberton-react-workshop-homework#10]
1. https://jsfiddle.net/raymondlf/cetnkg84/

2a. A closure is a function having access to the parent scope, even after the parent function has closed.

2b. A closure is where a function makes objects in its parent scope private objects. Life of an object in local scope ends when the scope is closed. However, a function can access objects in the scope "above" it, thus having closure, the object made private to a function closure can still live after function is closed. Also, the object in the closure can only be modified by the closure itself.

2c. https://jsfiddle.net/raymondlf/d30exfkL/

Typescript

1. https://jsfiddle.net/raymondlf/h3m9f5u1/
2. https://jsfiddle.net/raymondlf/9uLp7kaz/
3. https://jsfiddle.net/raymondlf/p4c8ft6y/
4. https://jsfiddle.net/raymondlf/3zoamfbu/
5. https://jsfiddle.net/raymondlf/7Lyj5pz6/
6. https://jsfiddle.net/raymondlf/9mpadzt4/
7. https://jsfiddle.net/raymondlf/fq3b1xjc/
8. https://jsfiddle.net/raymondlf/po10trmz/

Thanks
@p0x6

**Comment by p0x6** [comment]
LGTM!
