### ISSUE TITLE
Homework week 1

### ISSUE THREAD

**Issue by iamzinzi** [p0x6/holberton-react-workshop-homework#11]
1) Code: https://jsfiddle.net/iamzinzi/3ekj5m40/8/
Diagram: https://imgur.com/nKOvdSZ

2)
a) Closure is a feature in JavaScript of a function and its access to its local variables and its outer function's variables.
b)  Closure is a feature in JavaScript of a function and its access to its local variables and its outer function's variables. This is also called a scope chain. A closure has access to its own scope (defined within its curly braces), access to the outer function's scope, and access to the global scope. In C, after a function returns, all of its local variables are no longer accessible because the stack frame is destroyed. In JavaScript however, if you define a function within a function (nested function), the local variables of the outer function are still available to the inner function even when that outer function completes execution, creating a closure. If the outer function returns the inner function, it makes possible for a function to have "private" variables.
c) https://jsfiddle.net/iamzinzi/qrox4w3n/5/

3)
1) https://jsfiddle.net/iamzinzi/adsuqp0k/8/
2) https://jsfiddle.net/iamzinzi/ruqjeh36/7/
3) https://jsfiddle.net/iamzinzi/xd849vc3/7/
4) https://jsfiddle.net/iamzinzi/3j24okL1/5/
5) https://jsfiddle.net/iamzinzi/wneyk2zj/19/
6) https://jsfiddle.net/iamzinzi/fhbu2exw/3/
7) https://jsfiddle.net/iamzinzi/t6n7L95o/2/
8) https://jsfiddle.net/iamzinzi/wakjzy3v/1/
Thank you!
@p0x6

**Comment by p0x6** [comment]
LGTM!
