### ISSUE TITLE
holberton-react-ws-hw1

### ISSUE THREAD

**Issue by jsjimenez51** [p0x6/holberton-react-workshop-homework#12]
1) [-> click here <-](https://jsfiddle.net/Jsjimenez51/uc5kasmz/11/)

2a) Closures refer to the lexical environment that defines the scope/access of a function.
2b) Closures refer to the scope aka lexical environment that is created within/around a function. In general, variables are declared on the global scope and are hoisted meaning that they are accessible at any level within a function.  With closures, you are able to give those variables local scope creating pseudo "private" variables and limiting access to those variables to a local scope. Thus closures give you the ability to influence access and the ability to overwrite variables in different scopes.
2c) [-> click here <- ](https://jsfiddle.net/Jsjimenez51/9fsq7nzb/20/)

Typescript
1) [https://jsfiddle.net/Jsjimenez51/56dgfjbu/10/](https://jsfiddle.net/Jsjimenez51/56dgfjbu/10/)
2) [https://jsfiddle.net/Jsjimenez51/trvq9L35/12/](https://jsfiddle.net/Jsjimenez51/trvq9L35/12/)
3) [https://jsfiddle.net/Jsjimenez51/568jsxL9/](https://jsfiddle.net/Jsjimenez51/568jsxL9/)
4) [https://jsfiddle.net/Jsjimenez51/wfu2k10x/5/](https://jsfiddle.net/Jsjimenez51/wfu2k10x/5/)
5) [https://jsfiddle.net/Jsjimenez51/wLb3kvzf/3/](https://jsfiddle.net/Jsjimenez51/wLb3kvzf/3/)
6) [https://jsfiddle.net/Jsjimenez51/gk8d0jfz/]( https://jsfiddle.net/Jsjimenez51/gk8d0jfz/)
7) [https://jsfiddle.net/Jsjimenez51/bxjtskfg/1/](https://jsfiddle.net/Jsjimenez51/bxjtskfg/1/)
8) [https://jsfiddle.net/Jsjimenez51/wbm8neaf/](https://jsfiddle.net/Jsjimenez51/wbm8neaf/)

@p0x6

**Comment by p0x6** [comment]
LGTM!
