### ISSUE TITLE
Auditing, hope it's okay that I submit the work!

### ISSUE THREAD

**Issue by robertglatzel** [p0x6/holberton-react-workshop-homework#13]
1:
 https://imgur.com/a/LRfG2bF

2:
    * Closure is when a function located inside of another function has access to the outer functions / scopes variables.
    * Closure is when a function located inside of another function has access to the outer functions / scopes variables. This is referred to as a scope chain, and a closure has three scope chains: It has access to the variables within it's scope, access to variables in the scope of the enclosing function, and access to global variables. Normally when a function executes and ends, the variables created inside that function also disappear. But, because of closure the 
variables of the outer function are still available to the inner function because they are actually preserved and are accessible.

 * https://jsfiddle.net/j08t6mac/1/

3:
    1 - https://jsfiddle.net/ueost7mx/4/
    2 - https://jsfiddle.net/ueost7mx/2/
    3 - https://jsfiddle.net/ueost7mx/5/
    4 - https://jsfiddle.net/ueost7mx/6/
    5 - https://jsfiddle.net/ueost7mx/7/
    6 - https://jsfiddle.net/ueost7mx/9/
    7 - https://jsfiddle.net/ueost7mx/10/
    8 - https://jsfiddle.net/ueost7mx/12/

@p0x6

**Comment by p0x6** [comment]
LGTM!
