### ISSUE TITLE
React workshop Week 1 homework

### ISSUE THREAD

**Issue by hcheung01** [p0x6/holberton-react-workshop-homework#14]
1) Link to psudo code / diagram
2a) Closures gives you access to an outer function’s scope from an inner function
2b) The primary goal of closures is to ensure data privacy by creating a protective wrapper function. Closure is the combination of a function enclosed together with references to its surrounding lexical environment. In Javascript, closures are created every time a function is created, at function creation time. To use a closure, define function inside another function and expose it. To expose the function, return it or pass it to another function.
2c) https://jsfiddle.net/C0MPL3XM1ND/1z3642dp/24/

Typescript
1) https://jsfiddle.net/C0MPL3XM1ND/jynLh6df/2/
2) https://jsfiddle.net/C0MPL3XM1ND/48g35ruv/29/
3) https://jsfiddle.net/C0MPL3XM1ND/x4c8fptr/52/
4) https://jsfiddle.net/C0MPL3XM1ND/q1sznp6d/26/
5) https://jsfiddle.net/C0MPL3XM1ND/Lgobk76r/32/
6) https://jsfiddle.net/C0MPL3XM1ND/cdjk0v6p/10/
7) https://jsfiddle.net/C0MPL3XM1ND/fL5xtsjm/3/
8) https://jsfiddle.net/C0MPL3XM1ND/9wod8t1h/4/

@p0x6

**Comment by p0x6** [comment]
LGTM!
