### ISSUE TITLE
HW1

### ISSUE THREAD

**Issue by kevanlucc** [p0x6/holberton-react-workshop-homework#15]
1) https://jsfiddle.net/beya3zLm/
2a) A closure is a function that remembers its outer variables and can access them.
2b) In JavaScript, all functions are naturally closures , they automatically remember where they were created using a hidden [[Environment]] property, 
and all of them can access outer variables.
2C) https://jsfiddle.net/kevanlucc/2n0co49t/3/

Typescript
1. https://jsfiddle.net/rndek12o/
2. https://jsfiddle.net/kevanlucc/fpmzwtbs/1/
3. 
4. https://jsfiddle.net/kevanlucc/f1ov9daq/1/
5. https://jsfiddle.net/kevanlucc/k5rcyxbm/3/
6.  https://jsfiddle.net/kevanlucc/2nobt0u4/1/
7. https://jsfiddle.net/kevanlucc/wjrL16ng/1/
8. https://jsfiddle.net/kevanlucc/ejgz9avy/

@p0x6

**Comment by p0x6** [comment]
LGTM!
