### ISSUE TITLE
WK-1 Homework

### ISSUE THREAD

**Issue by anovacap** [p0x6/holberton-react-workshop-homework#2]
Name - Damon
slack - Damon
1) https://jsfiddle.net/anovacap/1dxbf3jL/84/
2a) a closure is a function nested inside of another function, creating a variable scope chain.
2b) a closure is a function nested inside of another function, creating a variable scope chain. The inner function has access to its own variables. the inner function has access to the outer functions variable. The inner function has access to the global variables.
2c) https://jsfiddle.net/anovacap/1dxbf3jL/93/

Typescript
1) https://jsfiddle.net/anovacap/1dxbf3jL/98/
2) https://jsfiddle.net/anovacap/1dxbf3jL/104/
3) https://jsfiddle.net/anovacap/1dxbf3jL/107/
4) https://jsfiddle.net/anovacap/1dxbf3jL/108/
5) https://jsfiddle.net/anovacap/1dxbf3jL/111/
6) https://jsfiddle.net/anovacap/1dxbf3jL/114/
7) https://jsfiddle.net/anovacap/1dxbf3jL/117/
8) https://jsfiddle.net/anovacap/1dxbf3jL/119/
@p0x6

**Comment by p0x6** [comment]
LGTM!
