### ISSUE TITLE
Javascript is trash... Typescript is life. -- Bobby during first workshop 

### ISSUE THREAD

**Issue by byn3** [p0x6/holberton-react-workshop-homework#3]
1) My explanation is here - https://jsfiddle.net/53me6rnj/ using the problem from last week. But honestly, there is way better descriptions out there. https://stackoverflow.com/questions/23948198/variable-environment-vs-lexical-environment
https://hackernoon.com/javascript-execution-context-and-lexical-environment-explained-528351703922

2a) You can use variables located in outer functions.
2b) Functions can use global variables and outside variables. Functions can use its own inner variables. Functions cannot use other functions' inner variables. Local variables are hidden from other functions and is better for security.
2c) https://jsfiddle.net/53me6rnj/1/

3-1) https://jsfiddle.net/53me6rnj/2/
3-2) https://jsfiddle.net/53me6rnj/3/
3-3) https://jsfiddle.net/53me6rnj/4/
3-4) https://jsfiddle.net/cjtgbw8o/
3-5) https://jsfiddle.net/53me6rnj/6/
3-6) https://jsfiddle.net/53me6rnj/7/
3-7) https://jsfiddle.net/xszebh3j/
3-8) https://jsfiddle.net/6o5zrmq1/

@p0x6

**Comment by p0x6** [comment]
LGTM!
