### ISSUE TITLE
Week 1 homework

### ISSUE THREAD

**Issue by thenicopixie** [p0x6/holberton-react-workshop-homework#4]
1.) https://jsfiddle.net/Nicole_Swanson/34zp98g2/
2.) Closures
  2a.) In JavaScript, a closure is where a inner function has access to the outer enclosing function variables, thus creating a scope chain
  2b.) A closure is where a inner function has access to the outer enclosing function variables, thus creating a scope chain. A closure has access its own scope. The variables defined inside a function are available to that function. It also has access to the outer functions variables and global variables.
  2c.) JavaScript counter  (https://jsfiddle.net/Nicole_Swanson/a2xrdp16/)

3.) Typescript
  1.) https://jsfiddle.net/Nicole_Swanson/3qvjndtr/
  2.) https://jsfiddle.net/Nicole_Swanson/1r6u83q2/
  3.) https://jsfiddle.net/Nicole_Swanson/x8o2pued/
  4.) https://jsfiddle.net/Nicole_Swanson/2mj0odsg/
  5.) https://jsfiddle.net/Nicole_Swanson/c4609edt/
  6.) https://jsfiddle.net/Nicole_Swanson/d24bv7h9/
  7.) https://jsfiddle.net/Nicole_Swanson/hg5n9o0d/
  8.) https://jsfiddle.net/Nicole_Swanson/y107z9dv/

**Comment by p0x6** [comment]
LGTM!
