### ISSUE TITLE
Brennan HW1

### ISSUE THREAD

**Issue by bdbaraban** [p0x6/holberton-react-workshop-homework#5]
1) https://imgur.com/a/2Cyp1SJ
Not sure what came over me, but I ended up writing a blog post diving into this topic. If you get a chance (and truly only if - no pressure!), would you mind giving it a look-over for me? https://medium.com/@bdov_/javascript-typescript-execution-vs-lexical-vs-variable-environment-37ff3f264831

2a) JavaScript closures refer to functions that can access outer variables.
2b) The execution of a function, code block or script in JavaScript generates a lexical environment. The lexical environment is an object containing an environment record storing locally-scoped memory as well as a reference to the outer lexical environment. Closures refer to nested functions with outer lexical environment references referencing and making accessible parent environment records. All functions in JavaScript are closures.
2c) https://jsfiddle.net/bdbaraban/2khx9do3/

TypeScript
1) https://jsfiddle.net/bdbaraban/h9qp8uxo/1/
2) https://jsfiddle.net/bdbaraban/3moxrvhk/1/
3) https://jsfiddle.net/bdbaraban/eoq7rLbu/
4) https://jsfiddle.net/bdbaraban/uwq0r4do/2/
5) https://jsfiddle.net/bdbaraban/6czbpnya/1/
6) https://jsfiddle.net/bdbaraban/gtLa35vk/
7) https://jsfiddle.net/bdbaraban/arn2s4vb/1/
8) https://jsfiddle.net/bdbaraban/jLq8zntu/

Thanks Bobby!

**Comment by p0x6** [comment]
LGTM!
