### ISSUE TITLE
React workshop hw1 (jogden)

### ISSUE THREAD

**Issue by jogden4195** [p0x6/holberton-react-workshop-homework#6]
1.) [Diagram](https://docs.google.com/document/d/1yiXofF0iSH2vJiF-6hWwqBuSsryQEaalkYz9a0HbB38/edit?usp=sharing)
2a.) A **closure** is when an inner function has access to the parent function's variables (aka a scope chain).
2b.) A **closure** is when an inner function has access to the parent function's variables (aka a scope chain). A closure contains 3 scope chains, meaning it has access to three different scopes; the first scope is its own scope, aka the variables defined between its curly brackets; the second access is to the parent function's variables, and the third access is to the global variables. Closures have access to its parent function even after the parent function has closed. Therefore, closures make it possible for a function to have "private" variables.
2c.) [Answer](https://jsfiddle.net/jLvekdtc/)
3.)
1. [Fat Arrow Exercise](https://jsfiddle.net/1hxfk06j/)
2. [Destructuring Exercise](https://jsfiddle.net/ofb25qny/)
3. [Destructuring and Map() Exercise](https://jsfiddle.net/wL3g1qvo/)
4. [ES6 Classes Exercise](https://jsfiddle.net/wL3g1qvo/3/)
5. [ES6 classes Exercise #2](https://jsfiddle.net/wL3g1qvo/2/)
6. [Rest Operator Exercise](https://jsfiddle.net/wL3g1qvo/4/)
7. [Spread Operator Exercise](https://jsfiddle.net/wL3g1qvo/5/)
8. [Rest Operator Exercise #2](https://jsfiddle.net/wL3g1qvo/6/)
@p0x6

**Comment by p0x6** [comment]
LGTM!
