### ISSUE TITLE
Week 1 Homework

### ISSUE THREAD

**Issue by suhearsawho** [p0x6/holberton-react-workshop-homework#8]
1. https://imgur.com/a/VHNSbhv
I did not include more information on the lexical environment and variable environment associated with each execution context. Please let me know if you wish for me to do so! 
Credits to: https://tylermcginnis.com/ultimate-guide-to-execution-contexts-hoisting-scopes-and-closures-in-javascript/

2A. A closure is a function that is able to access its outer variables, or variables of a parent function that may or may not be closed. 
2B. A closure can be seen as an amalgamation of a function and associated lexical environment from where it was formed. It is a function  that remembers the environment that it came from through a hidden [[Environment]] property. As a result of this property, a function can access outer variables. All functions, by default, are closures in Javascript (this does not include new Function)
2C. https://jsfiddle.net/p41tg7qx/1/

Typescript
1. https://jsfiddle.net/dv56abmg/
2. https://jsfiddle.net/3w8c9vaL/
3. https://jsfiddle.net/0otpeu3L/
4. https://jsfiddle.net/2be983nx/
5. https://jsfiddle.net/n4kshjza/
6. https://jsfiddle.net/7nwax5p4/
7. https://jsfiddle.net/hewmyn0j/
8. https://jsfiddle.net/p41tg7qx/

Thank you! :) 
@p0x6

**Comment by p0x6** [comment]
LGTM!
